"use client";

import {
  InvoiceData,
} from "../types";

interface Props {

  invoice: InvoiceData;

}

export function InvoiceFooter({

  invoice,

}: Props) {

  return (

    <div className="mt-10 border-t pt-6">

      {/* Thank You */}

      <div className="text-center">

        <h3 className="text-xl font-semibold">

          Thank You!

        </h3>

        <p className="mt-2 text-sm text-gray-600">

          Thank you for choosing Doorify.
          We appreciate your business and will
          complete your order with the highest
          quality and care.

        </p>

      </div>

      {/* Company */}

      <div className="mt-8 grid grid-cols-2 gap-8 text-sm">

        <div>

          <h4 className="font-semibold">

            Prepared By

          </h4>

          <p className="mt-2">

            {invoice.salesperson.name || "-"}

          </p>

        </div>

        <div className="text-right">

          <h4 className="font-semibold">

            Contact

          </h4>

          <p className="mt-2">

            Doorify

          </p>

          <p>

            +91 XXXXX XXXXX

          </p>

          <p>

            support@doorify.in

          </p>

        </div>

      </div>

      {/* Notes */}

      <div className="mt-8 rounded-lg border bg-gray-50 p-4 text-xs text-gray-600">

        <p className="font-semibold">

          Notes

        </p>

        <ul className="mt-2 list-disc space-y-1 pl-5">

          <li>

            This document serves as an order
            confirmation invoice.

          </li>

          <li>

            Please verify all sizes,
            quantities and customizations
            before manufacturing begins.

          </li>

          <li>

            Only the selected
            customizations are included in
            this invoice.

          </li>

          <li>

            Customization images are for
            reference only.

          </li>

          <li>

            Remaining payment (if any) must
            be cleared before dispatch.

          </li>

        </ul>

      </div>

      {/* Bottom */}

      <div className="mt-8 text-center text-xs text-gray-500">

        Generated by Doorify

      </div>

    </div>

  );

}