import {
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

import {
  InvoiceData,
} from "../types";


interface Props {

  invoice: InvoiceData;

}


export function InvoicePdfFooter({

  invoice,

}: Props) {


  return (

    <View style={styles.container}>


      {/* =====================================
          Thank You
      ====================================== */}

      <View style={styles.thankYou}>


        <Text style={styles.thankTitle}>

          Thank You!

        </Text>


        <Text style={styles.description}>

          Thank you for choosing Doorify.
          We appreciate your business and will
          complete your order with the highest
          quality and care.

        </Text>


      </View>



      {/* =====================================
          Company Details
      ====================================== */}

      <View style={styles.companyRow}>


        <View>


          <Text style={styles.heading}>

            Prepared By

          </Text>


          <Text style={styles.text}>

            {
              invoice.salesperson.name ||
              "-"
            }

          </Text>


        </View>



        <View style={styles.contact}>


          <Text style={styles.heading}>

            Contact

          </Text>


          <Text style={styles.text}>

            Doorify

          </Text>


          <Text style={styles.text}>

            +91 XXXXX XXXXX

          </Text>


          <Text style={styles.text}>

            support@doorify.in

          </Text>


        </View>


      </View>




      {/* =====================================
          Notes
      ====================================== */}

      <View style={styles.notes}>


        <Text style={styles.notesTitle}>

          Notes

        </Text>



        <Text style={styles.noteItem}>

          • This document serves as an order
          confirmation invoice.

        </Text>



        <Text style={styles.noteItem}>

          • Please verify all sizes,
          quantities and customizations
          before manufacturing begins.

        </Text>



        <Text style={styles.noteItem}>

          • Only the selected customizations
          are included in this invoice.

        </Text>



        <Text style={styles.noteItem}>

          • Customization images are for
          reference only.

        </Text>



        <Text style={styles.noteItem}>

          • Remaining payment (if any) must
          be cleared before dispatch.

        </Text>


      </View>




      {/* =====================================
          Bottom
      ====================================== */}

      <Text style={styles.generated}>

        Generated by Doorify

      </Text>


    </View>

  );

}



const styles = StyleSheet.create({


  container: {

    marginTop: 40,

    paddingTop: 24,

    borderTopWidth: 1,

    borderTopColor: "#e5e7eb",

  },


  thankYou: {

    alignItems: "center",

  },


  thankTitle: {

    fontSize: 18,

    fontWeight: 700,

  },


  description: {

    marginTop: 8,

    fontSize: 10,

    color: "#4b5563",

    textAlign: "center",

    lineHeight: 14,

  },


  companyRow: {

    marginTop: 32,

    flexDirection: "row",

    justifyContent: "space-between",

  },


  contact: {

    alignItems: "flex-end",

  },


  heading: {

    fontSize: 11,

    fontWeight: 700,

    marginBottom: 8,

  },


  text: {

    fontSize: 10,

    marginBottom: 3,

  },


  notes: {

    marginTop: 32,

    padding: 16,

    borderWidth: 1,

    borderColor: "#e5e7eb",

    borderRadius: 8,

    backgroundColor: "#f9fafb",

  },


  notesTitle: {

    fontSize: 10,

    fontWeight: 700,

    marginBottom: 8,

  },


  noteItem: {

    fontSize: 9,

    color: "#4b5563",

    marginBottom: 6,

    lineHeight: 12,

  },


  generated: {

    marginTop: 28,

    textAlign: "center",

    fontSize: 9,

    color: "#6b7280",

  },


});